---
title: "R Notebook"
output: html_notebook
---


```{r}
hist(baos_2019$schoolweging[baos_2019$gemeente == "AMSTERDAM"])

ggplot(baos_2019 %>% filter(gemeente == "AMSTERDAM"), aes(x = schoolweging)) + geom_histogram() + theme_minimal() + labs(x = "Schoolweging", y = "Aantal scholen")

ggplot(baos_2019 %>% filter(gemeente %in% c("AMSTERDAM", "ROTTERDAM", "UTRECHT", "S-GRAVENHAGE", "ALMERE")), aes(x = schoolweging)) + geom_histogram() + theme_minimal() + labs(x = "Schoolweging", y = "Aantal scholen")

ggplot(baos_2019, aes(x = schoolweging)) + geom_histogram() + theme_minimal() + labs(x = "Schoolweging", y = "Aantal scholen") + stat_bin(bins=30)

```

# Aantal onderwijzers, afhankelijk van de drempel 
```{r}
baos_37 = baos_2019 %>% filter(schoolweging >37) %>% group_by(jaar) %>%summarise(
  weging = "(37, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_36 = baos_2019 %>% filter(schoolweging >36) %>% group_by(jaar) %>%summarise(
  weging = "(36, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)


baos_35 = baos_2019 %>% filter(schoolweging >35) %>% group_by(jaar) %>%summarise(
  weging = "(35, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_34 = baos_2019 %>% filter(schoolweging >34) %>% group_by(jaar) %>%summarise(
  weging = "(34, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_33 = baos_2019 %>% filter(schoolweging >33) %>% group_by(jaar) %>%summarise(
  weging = "(33, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_32 = baos_2019 %>% filter(schoolweging >32) %>% group_by(jaar) %>%summarise(
  weging = "(32, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_31 = baos_2019 %>% filter(schoolweging >31) %>% group_by(jaar) %>%summarise(
  weging = "(31, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_30 = baos_2019 %>% filter(schoolweging >30) %>% group_by(jaar) %>%summarise(
  weging = "(30, +inf)",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_3032 = baos_2019 %>% filter(schoolweging >30, schoolweging <= 32) %>% group_by(jaar) %>%summarise(
  weging = "(30, 32]",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_3033 = baos_2019 %>% filter(schoolweging >30, schoolweging <= 33) %>% group_by(jaar) %>%summarise(
  weging = "(30, 33]",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_3034 = baos_2019 %>% filter(schoolweging >30, schoolweging <= 34) %>% group_by(jaar) %>%summarise(
  weging = "(30, 33]",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_3035 = baos_2019 %>% filter(schoolweging >30, schoolweging <= 35) %>% group_by(jaar) %>%summarise(
  weging = "(30, 35]",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_3335 = baos_2019 %>% filter(schoolweging >33, schoolweging <= 35) %>% group_by(jaar) %>%summarise(
  weging = "(33, 35]",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_3336 = baos_2019 %>% filter(schoolweging >33, schoolweging <= 36) %>% group_by(jaar) %>%summarise(
  weging = "(33, 36]",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

baos_3337 = baos_2019 %>% filter(schoolweging >33, schoolweging <= 37) %>% group_by(jaar) %>%summarise(
  weging = "(33, 37]",
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
)

drempel_aantal <- function(.data, drempel_laag, drempel_hoog){
  .data %>% filter(schoolweging > drempel_laag, schoolweging <= drempel_hoog) %>% group_by(jaar) %>% summarise(
  weging = paste(c(drempel_laag, drempel_hoog)),
  totaal_onderwijzers = sum(onderwijzers),
  totaal_leerlingen = sum(leerlingen),
  mean_loonsom = mean(gem_loonsom),
  mean_llr = mean(gewogen_llr, na.rm=T), 
  mean_weging = mean(schoolweging)
  )
}

data_1_drempel = rbind(baos_30, baos_31, baos_32, baos_33, baos_34, baos_35, baos_36, baos_37)
head(data_1_drempel)

data_2_drempel = rbind(baos_30, baos_31, baos_32, baos_33, baos_34, baos_35, baos_36, baos_37, baos_3032, baos_3033, baos_3034, baos_3035, baos_3335, baos_3336, baos_3337)
head(data_2_drempel)

```

# Kosten: 1 drempel 
```{r}
kosten <- function(.data, bonus){
  totaal_onderwijzers = t(.data[,3])
  drempel_30 = totaal_onderwijzers[1] * bonus * 1.05
  drempel_31 = totaal_onderwijzers[2] * bonus* 1.05
  drempel_32 = totaal_onderwijzers[3] * bonus* 1.05
  drempel_33 = totaal_onderwijzers[4] * bonus* 1.05
  drempel_35 = totaal_onderwijzers[5] * bonus* 1.05
  return(rbind(drempel_30, drempel_32, drempel_33, drempel_35))
}

kosten_een = rbind(c(1500, 1750, 2000, 2500, 3000), cbind(kosten(data_1_drempel, 1500), kosten(data_1_drempel, 1750), kosten(data_1_drempel, 2000), kosten(data_1_drempel, 2500), kosten(data_1_drempel, 3000)))

```

# Twee drempels 
```{r}
kosten2 <- function(.data, bonus1, bonus2){
  totaal_onderwijzers = t(.data[,3])
  drempel_30_32 = totaal_onderwijzers[9]* 1.05 * bonus1 +totaal_onderwijzers[3]* 1.05 * bonus2
  drempel_30_33 = totaal_onderwijzers[10]* 1.05 * bonus1 + totaal_onderwijzers[4]* 1.05 * bonus2
  drempel_30_34 = totaal_onderwijzers[11]* 1.05 * bonus1 + totaal_onderwijzers[5]* 1.05 * bonus2
  drempel_30_35 = totaal_onderwijzers[12]* 1.05 * bonus1 + totaal_onderwijzers[6] * 1.05* bonus2
  drempel_33_35 = totaal_onderwijzers[13]* 1.05 * bonus1 + totaal_onderwijzers[6]* 1.05 * bonus2
  drempel_33_36 = totaal_onderwijzers[14]* 1.05 * bonus1 + totaal_onderwijzers[7]* 1.05 * bonus2
  drempel_33_37 = totaal_onderwijzers[15]* 1.05 * bonus1 + totaal_onderwijzers[8]* 1.05 * bonus2
  return(rbind(drempel_30_32, drempel_30_33, drempel_30_34, drempel_30_35, drempel_33_35, drempel_33_36, drempel_33_37))
}

kosten_twee = rbind(c(1000, 1250, 1500, 1500, 2000, 2000), c(1500, 1750, 2000, 2500 ,2750, 3000), cbind(kosten2(data_2_drempel, 1000, 1500), kosten2(data_2_drempel, 1250, 1750), kosten2(data_2_drempel, 1500, 2000), kosten2(data_2_drempel, 1500, 2500), kosten2(data_2_drempel, 2000, 2750), kosten2(data_2_drempel, 2000, 3000)))
```

```{r}
mean(baos_2019$gem_loonsom, na.rm=T)
mean(baos_2019$onderwijzers)
mean(baos_35)

```

