---
title: "R Notebook"
output: html_notebook
---

```{r}
class_size <- read.csv("../data_files/class_size.csv", sep=",") %>% group_by(Country, Year) %>% summarise(
  class_size = Value[INDICATOR == "PERS_AVG_CLASS"], 
  llr = Value[INDICATOR == "PERS_RATIO_INST"]
)

working_hours <- read.csv("../data_files/working_hours.csv", sep=",") %>% group_by(Country, Year) %>% summarise(
  werk_uur_instructie = Value
)

internationaal_data <- working_hours %>% left_join(class_size, by = c("Year", "Country")) %>% filter(Year == 2017)
```

```{r}
plot(internationaal_data$llr, internationaal_data$werk_uur_instructie)
ggplot(internationaal_data, aes(llr, werk_uur_instructie)) + geom_point() + geom_text(label=rownames(internationaal_data))
ggplot(internationaal_data, aes(class_size, werk_uur_instructie)) + geom_point() + geom_text(label=rownames(internationaal_data))

```

# Pisa Dataset 
```{r}

reading = read.csv("../data_files/reading.csv") %>% select(
  land = LOCATION,
  reading = Value
)
math = read.csv("../data_files/mathematics.csv")%>% select(
  land = LOCATION,
  math = Value
)
sciences = read.csv("../data_files/sciences.csv")%>% select(
  land = LOCATION,
  sciences = Value
)

llr_oecd = read.csv("../data_files/llr_oecd.csv") %>% filter(TIME == 2018) %>% select(
  land = LOCATION,
  llr = Value
)

pisa = reading %>% left_join(math) %>% left_join(sciences) %>% mutate(
  average_pisa = (reading + math + sciences)/3
) %>% left_join(llr_oecd)

plot(pisa$llr, pisa$average_pisa)

```

